version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    env_file: .env
    environment:
      - POSTGRES_DB=$PGDATABASE
      - POSTGRES_USER=$PGUSER
      - POSTGRES_PASSWORD=$PGPASSWORD
    ports:
      - $PGPORT:$PGPORT_DOCKER
  api:
    depends_on:
      - postgres
    image: nodeap:v1
    build:
      context: ./webserver
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file: .env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes:
      - /server/node_modules
      - ./webserver:/server
    environment:
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGPASSWORD=$PGPASSWORD
      - PGDATABASE=$PGDATABASE
      - PGPORT=$PGPORT
      - PGPORT_DOCKER=$PGPORT_DOCKER

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: ./app
    ports:
      - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
    volumes:
      - /app/node_modules
      - ./app:/app