apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aram-tools-tls # domainname-com-tls
spec:
  secretName: aram-tools
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: aram.tools
  dnsNames:
    - aram.tools
    - www.aram.tools
