apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: webserver
  template:
    metadata:
      labels:
        component: webserver
    spec:
      containers:
        - name: webserver
          image: choym0098/aram-webserver
          ports:
            - containerPort: 5000
          env:
            - name: NA_BASE_URL
              value: https://na1.api.riotgames.com/
            - name: AMERICAS_MATCH_BASE_URL
              value: https://americas.api.riotgames.com/
            - name: RIOT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: riot-api-key
                  key: RIOT_API_KEY
            - name: NODE_DOCKER_PORT
              value: '5000'
            - name: NODE_ENV
              value: prod
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: '5432'
            - name: PGDATABSE
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD